name: MacOS SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
          set -e
          brew update
          brew install make python3 imagemagick
          pip3 install cogapp generate-iconset
          brew install mingw-w64 openal-soft freealut sdl2 sdl2_mixer glew
    - name: make
      run: make clean && OPENJKDF2_NO_ASAN=1 HOMEBREW_PREFIX=/usr/local make -f Makefile.macos
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-debug
        path: macos-package
