name: MacOS SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
          set -e
          brew update
          brew install cmake make python3 imagemagick
          pip3 install cogapp generate-iconset
          brew install mingw-w64 openal-soft sdl2 sdl2_mixer glew
    - name: cmake
      run: export HOMEBREW_PREFIX="/usr/local" && mkdir -p build_darwin64 && cd build_darwin64 && cmake .. && make
