name: Win64 SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential make python3 python3-pip bison imagemagick
          sudo pip3 install cogapp
          sudo apt-get install -y mingw-w64 clang libsdl2-dev libsdl2-mixer-dev libopenal-dev libglew-dev libalut-dev
    - name: make
      run: make -f Makefile.win64
